MATCH (ligand:ChemicalComponent)-[:HAS_ATOM]->(atom:Atom)
    RETURN atom.STEREO_CONFIG, atom.LEAVING_ATOM_FLAG, atom.ALT_ATOM_ID, atom.AROMATIC_FLAG, atom.ELEMENT_SYMBOL, atom.MODEL_CARTN_X_IDEAL, atom.MODEL_CARTN_Y_IDEAL, 
    atom.MODEL_CARTN_Z_IDEAL, atom.CHARGE, atom.ID LIMIT 50